version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deck_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3123:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/deck_db
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=production
    depends_on:
      - db

volumes:
  postgres_data:
